<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<!-- 屏蔽 CS1701/1702 程序集版本重定向警告，清理控制台输出 -->
		<NoWarn>1701;1702</NoWarn>
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
		
	</ItemGroup>

</Project>